### ISSUE TITLE
iam-ape update (PermissionError: [Errno 13] Permission denied)

### ISSUE THREAD

**Issue by duhaas2015** [orcasecurity/orca-toolbox#3]
Running python version 3.11.2
windows 10
iam-ape version (latest from install) 

running into issue when launching terminal as admin and running:

iam-ape --update

I keep getting:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\XXX\\AppData\\Local\\Temp\\tmp8u32qw9q'

**Comment by jhonnatan-costa** [comment]
I have an error when I run the command: iam-ape --arn arn:aws:iam::069560771595:role/account-creation-foundation

ERROR: Failed to load AWS IAM Actions due to file could not be opened successfully
File "c:\users\jhonnatan.costa\anaconda3\lib\site-packages\iam_ape\expand_policy.py", line 153, in expand_action
     for action in self.all_iam_actions[service].keys():
KeyError: 'servicecatalog'

**Comment by Tohar-orca** [comment]
solved in [1.1.2](https://github.com/orcasecurity/orca-toolbox/pull/8)
